* Captain Defend

** Description
Rouge-like tower-defense game.
The player has a base which they have to protect against coming enemies in night. The player will respawn upon death but when the base "dies" its game over or until the last has been won.
During the day the player can scavenge resources to upgrade their base.

*** Resources
The player can mine stones, cut trees or scavenge loot creates to get resources. With the resources the play can craft other items, such as weapons or tools and armor. They can also upgrade the base with better walls, fence and such.

*** Items
**** Weapons
Every weapon has an evolution
1. Knife (starting)
   Upgrade1: Machete
   Upgrade2: Sword

2. Pistol
   Upgrade1: Shotgun
   Upgrade2: Machinegun
**** Armor
The armor adds hp to the player. The player starts with 10 and with all upgrades 100.


*** House upgrades
1. Faster player respawn.

**** Defense
1. Walls giving the base better hp
2. Fence
   Starting:  tripwire (slows down enemies)
   upgrade1: wood fence (enemies has to destroy to enter)
   upgrpade2: stone fence (enemies has to destroy to enter but with health)
   upgrade3: barbed-wire does damage to enemies who the fence
3. Turrets
   upgrade1: Bow
   upgrade2: Machinegun turret
   upgrade3: Chicken shits eggs

*** Events
Some special rounds will be a themed at random. The enemies will be changed for themed ones.
The events can change drops from enemies and or damage and such things.

*** Mechanics overview
1. Looting and resource gathering
2. Upgrading items
3. Fighting enemies
